apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres1
  labels:
    app: postgres1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres1
  template:
    metadata:
      labels:
        app: postgres1
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "Admin1234"  # Change for security
            - name: POSTGRES_DB
              value: "mydatabase"

---
apiVersion: v1
kind: Service
metadata:
  name: bytebase-entrypoint-1
spec:
  selector:
    app: postgres1
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer
