apiVersion: v1
kind: PersistentVolume
metadata:
  name: splunk-pv
  labels:
    app: splunk
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  hostPath:
    path: "/mnt/splunk-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-pvc
  namespace: splunk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: splunk
  namespace: splunk
  labels:
    app: splunk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: splunk
  template:
    metadata:
      labels:
        app: splunk
    spec:
      containers:
      - name: splunk
        image: splunk/splunk:latest
        ports:
        - containerPort: 8000
        env:
        - name: SPLUNK_START_ARGS
          value: "--accept-license"
        - name: SPLUNK_PASSWORD
          value: "Splunk@123"
        volumeMounts:
        - mountPath: "/opt/splunk/var"
          name: splunk-storage
      volumes:
      - name: splunk-storage
        persistentVolumeClaim:
          claimName: splunk-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: splunk-service
  namespace: splunk
spec:
  selector:
    app: splunk
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer  # Change to NodePort if needed
